django/project_code/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
import requests

requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS = 'DEFAULT:@SECLEVEL=1'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_library/', include(('my_library.urls','my_library'),namespace = 'my_library')),
    path('users/', include(('users.urls','users'), namespace = 'users')),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset_password_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete')
]

django/users/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, re_path, include, reverse

from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    path('login/', views.my_login,name = 'login'),
    path('register/',views.my_register, name = 'register'),
    path('my_records/',views.my_records, name = 'my_records'),
    path('my_invoices/',views.my_invoice, name = 'my_invoices'),
    re_path(r'^my_invoices/(?P<invoice_id>\d+)/$', views.payment, name='payment'),
    path('logout/', LogoutView.as_view(next_page = 'users:login'), name='logout'),
    path('password_reset/Mptk/193gf89qhw1h3r834rh9123hr9fht412ht829fh/',views.reset,name = 'reset'),


]

django/users/models.py
from django.db import models

# Create your models here.

django/users/views.py
import datetime
from math import fabs

from django.shortcuts import render, redirect
from my_library.models import Customer, Record, Invoice, Payment
from django.contrib.auth import login,logout,authenticate
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required,permission_required
from django.contrib.auth.models import User
from django.urls import reverse
import django.utils.timezone as timezone
from decimal import *
from django.db.models import Max

# Create your views here.
def my_register(request):
    if request.method == "GET":
        return render(request, "users/new_register.html")
    #获取用户提供的数据
    else:
        username = request.POST.get("username")
        pwd = request.POST.get("password")
        fname = request.POST.get("firstname")
        lname = request.POST.get("lastname")
        passport = request.POST.get("passport")
        email = request.POST.get("email")
        mobile = request.POST.get("mobile")
        #添加到数据库,假设table名是UserInfo
        #UserInfo.objects.create(name = username, password = pwd, mobile = mobile)
        User.objects.create_superuser(username = username, password = pwd, email=email)
        id = User.objects.get_by_natural_key(username).id

        new_customer = Customer(customer_id =id,firstname= fname,lastname = lname,phonenumber = mobile,email = email, passport = passport)
        new_customer.save()
        return HttpResponseRedirect(reverse('users:login'))



def my_login(request):

    if request.method == 'GET':
        return render(request,'users/new_login.html')
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')
        remember = request.POST.get('remember')
        #使用Django自带的authenticat()函数判断是否有该用户
        user = authenticate(username=username,password=password)
        #如果存在该用户并且状态是激活的
        if user and user.is_active:
            #使用Django的login()函数进行登陆
            login(request,user)
            #如果记住登陆，则使用全局的过期时间，默认为2周
            if remember:
                # 设置为None，则表示使用全局的过期时间
                request.session.set_expiry(None)
            else:
                #否则设为0，关掉浏览器就注销登陆状态了
                request.session.set_expiry(0)
            #获取next页面（原本要访问的页面，因为没登陆所以转到login页面了），如果有的话则重定向到该页面
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return HttpResponseRedirect(reverse('my_library:books'))
        else:
            return HttpResponse('Wrong username or password')

# def my_logout(request):
#     logout(request)
#     return HttpResponseRedirect(reverse('my_library:index'))

@login_required
def my_records(request):
    customer_id = request.user.id
    records = Record.objects.filter(customer_id = customer_id)
    num = len(list(records))
    if request.method != 'POST':

        context = {'records':records, 'num':num}
        return render(request, 'users/new_my_records.html', context)
    else:
        for record in records:
            if str(record.record_id) in request.POST:

                this_record  =Record.objects.get(record_id = record.record_id)
                edate = record.expected_return_date
                adate = timezone.now()
                status = 'Late'
                if edate >= adate:
                    status = 'Return'
                this_record.actual_return_date = adate
                this_record.return_status = status
                this_record.save()
                return HttpResponseRedirect(reverse('users:my_records'))
@login_required
def my_invoice(request):
    customer_id = request.user.id
    #records = Record.objects.filter(customer_id = customer_id)
    invoices = Invoice.objects.filter(record__customer_id = customer_id).values('invoice_id','record__actual_return_date','invoice_status','invoice_amount')
    payments = Payment.objects.none()

    for invoice in invoices:
        payment = Payment.objects.filter(invoice = invoice['invoice_id'])
        payments = payments | payment
    num = len(invoices)
    num2 = len(payments)
    if request.method != 'POST':

        context = {'invoices':invoices, "payments":payments,'num':num, 'num2':num2}
        return render(request, 'users/new_my_invoices.html', context)

def reset(request):
    return render(request,'users/reset.html')
@login_required
def payment(request,invoice_id):
    invoice = Invoice.objects.get(invoice_id = invoice_id)
    context = {'invoice':invoice}
    if request.method != 'POST':
        return render(request, 'users/payment.html', context)
    else:
        method = request.POST.get('method')
        amount = request.POST.get('amount')
        amount = Decimal.from_float(float(amount))
        balance = invoice.invoice_amount - amount
        if balance < 0:
            balance = 0
        if fabs(balance) <= 1e-6:
            invoice.invoice_status = 1
        invoice.invoice_amount = balance
        invoice.save()

        max_record_id = Payment.objects.all().aggregate(max=Max('payment_id'))
        if not max_record_id['max']:
            id = 1
        else:
            id = max_record_id['max'] + 1
        new_payment = Payment(payment_id = id, paymentamount = amount, paymentmethod = method, invoice_id = invoice.invoice_id)
        new_payment.save()
        return HttpResponseRedirect(reverse('users:my_invoices'))

django/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<form action="" method="POST">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
    <table>
        <tbody>
            <tr>
                <td>用户名：</td>
                <td><input type="text" name="username"></td>
            </tr>
            <tr>
                <td>密码：</td>
                <td><input type="password" name="password"></td>
            </tr>
            <tr>
                <td>
                    <label for="">
                        <input type="checkbox" name="remember" value="1">记住我
                    </label>
                </td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="登录"></td>
            </tr>
        </tbody>
    </table>
</form>
</body>
</html>

django/templates/my_library/base.html
<p>
 {% if user.is_authenticated %}
 Hello, {{ user.username }}.
 <a href="{% url 'users:logout' %}">log out</a>-
 <a href="{% url 'my_library:books' %}">books</a>-
 <a href="{% url 'users:my_records' %}">my_records</a>-
 <a href="{% url 'users:my_invoices' %}">my_invoices</a>
 {% else %}
 <a href="{% url 'users:login' %}">log in</a>
 <a href="{% url 'users:register' %}">Sign up</a>
 {% endif %}
</p>
{% block content %}{% endblock content %}

django/templates/my_library/book.html
{% extends "my_library/base.html" %}
{% block content %}
 <p>{{ book.booknmae }}</p>
 <p>{{ book.topic }}</p>
 <p>Number of copies {{num}}</p>
<ul>
{% for copy in copys %}
<li>{{ copy.copy_id }}</li>
 <li>Available?{{ copy.availability }}
  {% if not copy.availability %}
  <input type="submit" name="{{copy.copy_id}}" value="Empty" class="button" disabled = "disabled"></input>
  {% else %}
  <form action="" method="post">
  {% csrf_token %}
   <input type="hidden" name="{{copy.copy_id}}" value=1>
   <button name="{{copy.copy_id}}borrow">borrow</button>
  </form>
  {% endif %}

 </li>
{% empty %}
 <li>No copy for this book.</li>
{% endfor %}
</ul>
{% endblock content %}

django/templates/my_library/copy_occupied.html
<p>
This copy has just been borrowed! -
 <a href="{% url 'my_library:books' %}">back</a>
</p>

django/templates/my_library/new_base.html

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Library Management System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- jQuery UI -->

    {% load static %}
    <link href="https://code.jquery.com/ui/1.10.3/themes/redmond/jquery-ui.css" rel="stylesheet" media="screen">
    <!-- Bootstrap -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- styles -->
    <link href="/static/css/styles.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<p>
 {% if user.is_authenticated %}
 Hello, {{ user.username }}.
 <a href="{% url 'users:logout' %}">log out</a>-
 <a href="{% url 'my_library:books' %}">books</a>-
 <a href="{% url 'users:my_records' %}">my_records</a>-
 <a href="{% url 'users:my_invoices' %}">my_invoices</a>
 {% else %}
 <a href="{% url 'users:login' %}">log in</a>
 <a href="{% url 'users:register' %}">Sign up</a>
 {% endif %}
</p>
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <!-- Logo -->
                <div class="logo">
                    <h1><a href="index.html">Library Management System</a></h1>
                </div>
            </div>
            <div class="col-md-5">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="input-group form">
<!--                            <input type="text" class="form-control" placeholder="Search...">-->
<!--                            <span class="input-group-btn">-->
<!--	                         <button class="btn btn-primary" type="button">搜索</button>-->
<!--	                       </span>-->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div class="navbar navbar-inverse" role="banner">
                    <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                                <ul class="dropdown-menu animated fadeInUp">
<!--                                    <li><a href="profile.html">Profile</a></li>-->
                                    <li><a href="{% url 'users:login' %}">log in</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

{% block content %}{% endblock content %}


<footer>
    <div class="container">
        <div class="copy text-center">
            Copyright 2021 <a href='#'>Website</a>
        </div>
    </div>
</footer>

{% load static %}
<link href="/static/vendors/datatables/dataTables.bootstrap.css" rel="stylesheet" media="screen">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery.js"></script>
<!-- jQuery UI -->
<script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/vendors/datatables/js/jquery.dataTables.min.js"></script>
<script src="/static/vendors/datatables/dataTables.bootstrap.js"></script>
<script src="/static/js/custom.js"></script>
<script src="/static/js/tables.js"></script>
</body>
</html>

django/templates/my_library/new_book.html

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Library Management System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- jQuery UI -->

    {% load static %}
    <link href="https://code.jquery.com/ui/1.10.3/themes/redmond/jquery-ui.css" rel="stylesheet" media="screen">
    <!-- Bootstrap -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- styles -->
    <link href="/static/css/styles.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<p>
 {% if user.is_authenticated %}
 Hello, {{ user.username }}.
 <a href="{% url 'users:logout' %}">log out</a>-
 <a href="{% url 'my_library:books' %}">books</a>-
 <a href="{% url 'users:my_records' %}">my_records</a>-
 <a href="{% url 'users:my_invoices' %}">my_invoices</a>
 {% else %}
 <a href="{% url 'users:login' %}">log in</a>
 <a href="{% url 'users:register' %}">Sign up</a>
 {% endif %}
</p>
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <!-- Logo -->
                <div class="logo">
                    <h1><a href="{%url 'my_library:index'%}">Library Management System</a></h1>
                </div>
            </div>
            <div class="col-md-5">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="input-group form">
<!--                            <input type="text" class="form-control" placeholder="Search...">-->
<!--                            <span class="input-group-btn">-->
<!--	                         <button class="btn btn-primary" type="button">搜索</button>-->
<!--	                       </span>-->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div class="navbar navbar-inverse" role="banner">
                    <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                                <ul class="dropdown-menu animated fadeInUp">
<!--                                    <li><a href="profile.html">Profile</a></li>-->
                                    <li><a href="{% url 'users:logout' %}">logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <div class="row">
        <div class="col-md-2">
            <div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
<!--                    <li><a href="index.html"><i class="glyphicon glyphicon-home"></i>首页</a></li>-->
                    {% load static %}
                    <li><a href="{% url 'users:my_records' %}"><i class="glyphicon glyphicon-list"></i> My Borrow List</a></li>
                    <li><a href="{% url 'my_library:books' %}"><i class="glyphicon glyphicon-record"></i> Book List</a></li>
                    <li><a href="{% url 'users:my_invoices' %}"><i class="glyphicon glyphicon-pencil"></i> My Invoices</a></li>
                    <li><a href="{% url 'my_library:rooms' %}"><i class="glyphicon glyphicon-list"></i> Rooms</a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-10">
            <div class="content-box-large">
                <div class="panel-heading">
                    <div class="panel-title">Book List</div>
                </div>
<!--                <div class="col-md-3 col-sm-6 pull-right add-btn">-->
<!--                    <a href="/add_author/" class="btn btn-info pull-right">Add Book-->
<!--                    </a>-->
<!--                </div>-->
                <div class="panel-body">
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
                        <thead>
                        <tr>
                            <th>Copy ID</th>
                            <th>Availability</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for copy in copys %}
                        <tr>
                            <td>{{ copy.copy_id }}</td>
                            <td>{{ copy.availability }}</td>
                            <td class="text-center">
                                {% load static %}
                                  {% if not copy.availability %}
                                  <input type="submit" name="{{copy.copy_id}}" value="Empty" class="button" disabled = "disabled"></input>
                                  {% else %}
                                  <form action="" method="post">
                                  {% csrf_token %}
                                   <input type="hidden" name="{{copy.copy_id}}" value=1>
                                   <button name="{{copy.copy_id}}borrow">borrow</button>
                                  </form>
                                  {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>



        </div>
    </div>
</div>


<footer>
    <div class="container">
        <div class="copy text-center">
            Copyright 2021 <a href='#'>Website</a>
        </div>
    </div>
</footer>

{% load static %}
<link href="/static/vendors/datatables/dataTables.bootstrap.css" rel="stylesheet" media="screen">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery.js"></script>
<!-- jQuery UI -->
<script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/vendors/datatables/js/jquery.dataTables.min.js"></script>
<script src="/static/vendors/datatables/dataTables.bootstrap.js"></script>
<script src="/static/js/custom.js"></script>
<script src="/static/js/tables.js"></script>
</body>
</html>




{% block content %}

{% endblock content %}

django/templates/my_library/new_books.html

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Library Management System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- jQuery UI -->

    {% load static %}
    <link href="https://code.jquery.com/ui/1.10.3/themes/redmond/jquery-ui.css" rel="stylesheet" media="screen">
    <!-- Bootstrap -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- styles -->
    <link href="/static/css/styles.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<p>
 {% if user.is_authenticated %}
 Hello, {{ user.username }}.
 <a href="{% url 'users:logout' %}">log out</a>-
 <a href="{% url 'my_library:books' %}">books</a>-
 <a href="{% url 'users:my_records' %}">my_records</a>-
 <a href="{% url 'users:my_invoices' %}">my_invoices</a>
 {% else %}
 <a href="{% url 'users:login' %}">log in</a>
 <a href="{% url 'users:register' %}">Sign up</a>
 {% endif %}
</p>
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <!-- Logo -->
                <div class="logo">
                    <h1><a href="{%url 'my_library:index'%}">Library Management System</a></h1>
                </div>
            </div>
            <div class="col-md-5">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="input-group form">
<!--                            <input type="text" class="form-control" placeholder="Search...">-->
<!--                            <span class="input-group-btn">-->
<!--	                         <button class="btn btn-primary" type="button">搜索</button>-->
<!--	                       </span>-->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div class="navbar navbar-inverse" role="banner">
                    <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                                <ul class="dropdown-menu animated fadeInUp">
<!--                                    <li><a href="profile.html">Profile</a></li>-->
                                    <li><a href="{% url 'users:logout' %}">logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <div class="row">
        <div class="col-md-2">
            <div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
<!--                    <li><a href="index.html"><i class="glyphicon glyphicon-home"></i>首页</a></li>-->
                    {% load static %}
                    <li><a href="{% url 'users:my_records' %}"><i class="glyphicon glyphicon-list"></i> My Borrow List</a></li>
                    <li class="current"><a href="{% url 'my_library:books' %}"><i class="glyphicon glyphicon-record"></i> Book List</a></li>
                    <li><a href="{% url 'users:my_invoices' %}"><i class="glyphicon glyphicon-pencil"></i> My Invoices</a></li>
                    <li><a href="{% url 'my_library:rooms' %}"><i class="glyphicon glyphicon-list"></i> Rooms</a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-10">
            <div class="content-box-large">
                <div class="panel-heading">
                    <div class="panel-title">Book List</div>
                </div>
<!--                <div class="col-md-3 col-sm-6 pull-right add-btn">-->
<!--                    <a href="/add_author/" class="btn btn-info pull-right">Add Book-->
<!--                    </a>-->
<!--                </div>-->
                <div class="panel-body">
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
                        <thead>
                        <tr>
                            <th>Book Name</th>
                            <th>Topic</th>
                            <th>View Copies</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for book in books %}
                        <tr>
                            <td>{{ book.booknmae }}</td>
                            <td>{{ book.topic }}</td>
                            <td class="text-center">
                                {% load static %}
                                <a class="btn btn-info btn-sm" href="/my_library/books/{{book.book_id}}/"><i
                                        class="fa fa-pencil fa-fw"
                                        aria-hidden="true"></i>View Copies
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>



        </div>
    </div>
</div>


<footer>
    <div class="container">
        <div class="copy text-center">
            Copyright 2021 <a href='#'>Website</a>
        </div>
    </div>
</footer>

{% load static %}
<link href="/static/vendors/datatables/dataTables.bootstrap.css" rel="stylesheet" media="screen">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery.js"></script>
<!-- jQuery UI -->
<script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/vendors/datatables/js/jquery.dataTables.min.js"></script>
<script src="/static/vendors/datatables/dataTables.bootstrap.js"></script>
<script src="/static/js/custom.js"></script>
<script src="/static/js/tables.js"></script>
</body>
</html>




{% block content %}

{% endblock content %}

django/templates/users/new_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>sign up</title>
    <style>
        body {
            background: url("/static/bobst.jpeg");
        }

        .rg_layout {
            width: 900px;
            height: 500px;
            border: 8px solid #EEEEEE;
            background-color: white;
            margin: auto;
        }

        .rg_left {
            float: left;
            margin: 15px;
        }
        .rg_center {
            float: left;
        }
        .rg_right {
            float: right;
            margin: 15px;
        }

        .rg_left > p:first-child {
            color:#FFD026;
            font-size: 20px;
        }

        .rg_left > p:last-child {
            color:#A6A6A6;
            font-size: 20px;
        }

        .rg_right > p:first-child {
            font-size: 15px;

        }
        .rg_right p a {
            color:pink;
        }

        .td_left {
            width: 100px;
            height: 45px;
            text-align: right;
        }
        .td_right {
            padding-left: 50px ;
        }

        #username, #password, #email, #name, #tel, #birthday, #checkcode {
            width: 251px;
            height: 32px;
            border: 1px solid #A6A6A6;
            border-radius: 5px;
            padding-left: 10px;
        }

        #checkcode {
            width: 110px;
        }

        #img_check {
            height: 32px;
            vertical-align: middle;
        }

        #btn_sub {
            width: 150px;
            height: 40px;
            background-color: #FFD026;
            border: 1px solid #FFD026 ;
        }

        .error {
            color:red;
        }
        #td_sub {
            padding-left: 150px;
        }
    </style>

</head>
<body>

<div class="rg_layout">

    <div class="rg_left">

        <p>USER LOGIN</p>
    </div>

    <div class="rg_center">
        <div class="rg_form">
            <form action="#" id="form" method="POST">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                <table>
                    <tr>
                        <td class="td_left"><label for="username">username</label></td>
                        <td class="td_right">
                            <input type="text" name="username" id="username" placeholder="username">
                            <span id="s_username" class="error"></span>
                        </td>
                    </tr>

                    <tr>
                        <td class="td_left"><label for="password">password</label></td>
                        <td class="td_right">
                            <input type="password" name="password" id="password" placeholder="password">
                            <span id="s_password" class="error"></span>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <label for="">
                                <input type="checkbox" name="remember" value="1">Remember me
                            </label>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="submit" value="登录"></td>
                    </tr>
                </table>

            </form>
        </div>
    </div>

    <div class="rg_right">
        <p>does not have an account?<a href="{% url 'users:register'%}"> sign up</a></p>
        <p>Forget your password?<a href="{% url 'reset_password'%}"> Reset Password</a></p>
    </div>

</div>

</body>
</html>